# Generated by Django 4.0.5 on 2022-11-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal_json', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createoperation',
            old_name='operation',
            new_name='operator_type',
        ),
    ]
