# Generated by Django 4.0.5 on 2022-11-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal_json', '0002_rename_operation_createoperation_operator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createoperation',
            name='operator_type',
            field=models.CharField(max_length=100),
        ),
    ]
